package commands

// Command represents a command and its description
type Command struct {
    Name        string
    Description string
}

// List of commands with descriptions
var Words = []Command{
    {"sudo", "Super User Do. Allows a user to run commands as an administrator"},
    {"cat", "Concatenate and display the content of files"},
    {"ls", "List directory contents"},
    {"cd", "Change the current directory"},
    {"pwd", "Print the current working directory"},
    {"touch", "Create an empty file"},
    {"mkdir", "Create a new directory"},
    {"rm", "Remove files or directories"},
    {"cp", "Copy files or directories"},
    {"mv", "Move or rename files or directories"},
    {"clear", "Clear the terminal screen"},
    {"exit", "Exit the shell"},
    {"echo", "Display a line of text"},
    {"man", "Display the manual for a command"},
    {"grep", "Search text using patterns"},
    {"find", "Search for files in a directory hierarchy"},
    {"chmod", "Change file modes or Access Control Lists"},
    {"chown", "Change file owner and group"},
    {"df", "Report file system disk space usage"},
    {"du", "Estimate file space usage"},
    {"head", "Output the first part of files"},
    {"tail", "Output the last part of files"},
    {"tar", "Store, list or extract files in an archive"},
    {"wget", "Retrieve files from the web"},
    {"curl", "Transfer data from or to a server"},
    {"ps", "Report a snapshot of current processes"},
    {"kill", "Send a signal to a process"},
    {"top", "Display Linux tasks"},
    {"htop", "Interactive process viewer"},
    {"ssh", "OpenSSH SSH client (remote login program)"},
    {"scp", "Secure copy (remote file copy program)"},
    {"nano", "Simple text editor"},
    {"vim", "Vi IMproved, a programmer's text editor"},
    {"apt-get", "A package handling utility for Debian-based distributions"},
    {"yum", "Package manager for RPM-based distributions"},
    {"ping", "Send ICMP ECHO_REQUEST to network hosts"},
    {"ifconfig", "Configure a network interface"},
    {"ip", "Show/manipulate routing, devices, policy routing and tunnels"},
    {"netstat", "Print network connections, routing tables, interface statistics, masquerade connections, and multicast memberships"},
    {"ss", "Another utility to investigate sockets"},
    {"mount", "Mount a file system"},
    {"umount", "Unmount file systems"},
    {"uname", "Print system information"},
    {"uptime", "Tell how long the system has been running"},
    {"whoami", "Print the current user id and name"},
    {"hostname", "Show or set the system's host name"},
    {"history", "Show the command history"},
    {"alias", "Create an alias for a command"},
    {"unalias", "Remove an alias"},
    {"env", "Show the environment variables"},
    {"export", "Set an environment variable"},
    {"source", "Execute commands from a file in the current shell"},
    {"su", "Switch user"},
    {"passwd", "Change user password"},
    {"useradd", "Create a new user"},
    {"usermod", "Modify a user account"},
    {"userdel", "Delete a user account"},
    {"groupadd", "Create a new group"},
    {"groupmod", "Modify a group"},
    {"groupdel", "Delete a group"},
    {"crontab", "Schedule periodic background jobs"},
    {"at", "Schedule a command to run once at a later time"},
    {"jobs", "List active jobs"},
    {"bg", "Place a job in the background"},
    {"fg", "Place a job in the foreground"},
    {"killall", "Kill processes by name"},
    {"xargs", "Build and execute command lines from standard input"},
    {"tee", "Read from standard input and write to standard output and files"},
    {"diff", "Compare files line by line"},
    {"patch", "Apply a diff file to an original"},
    {"sed", "Stream editor for filtering and transforming text"},
    {"awk", "Pattern scanning and processing language"},
    {"tr", "Translate or delete characters"},
    {"cut", "Remove sections from each line of files"},
    {"sort", "Sort lines of text files"},
    {"uniq", "Report or omit repeated lines"},
    {"wc", "Print newline, word, and byte counts for each file"},
    {"basename", "Strip directory and suffix from filenames"},
    {"dirname", "Strip last component from file name"},
    {"readlink", "Print value of a symbolic link or canonical file name"},
    {"ln", "Make links between files"},
    {"stat", "Display file or file system status"},
    {"file", "Determine file type"},
    {"strings", "Print the strings of printable characters in files"},
    {"md5sum", "Compute and check MD5 message digest"},
    {"sha256sum", "Compute and check SHA256 message digest"},
    {"gzip", "Compress files"},
    {"gunzip", "Decompress files"},
    {"bzip2", "Compress files with bzip2"},
    {"bunzip2", "Decompress files with bzip2"},
    {"zip", "Package and compress files"},
    {"unzip", "Extract compressed files"},
    {"rar", "Archive manager for .rar files"},
    {"unrar", "Extract .rar files"},
    {"7z", "File archiver with high compression ratio"},
    {"7za", "Standalone version of 7z"},
    {"7zr", "Reduced version of 7z"},
    {"free", "Display memory usage"},
    {"who", "Show who is logged on"},
    {"last", "Show listing of last logged in users"},
    {"dmesg", "Print or control the kernel ring buffer"},
    {"lsblk", "List information about block devices"},
    {"blkid", "Locate/print block device attributes"},
    {"fdisk", "Partition table manipulator for Linux"},
    {"mkfs", "Build a Linux file system"},
    {"fsck", "File system consistency check and repair"},
    {"parted", "A partition manipulation program"},
    {"dd", "Convert and copy a file"},
    {"sync", "Flush file system buffers"},
    {"shutdown", "Halt, power-off or reboot the machine"},
    {"reboot", "Reboot the system"},
    {"docker run", "Run a command in a new container"},
    {"docker start", "Start one or more stopped containers"},
    {"docker stop", "Stop one or more running containers"},
    {"docker restart", "Restart one or more containers"},
    {"docker kill", "Kill one or more running containers"},
    {"docker rm", "Remove one or more containers"},
    {"docker rmi", "Remove one or more images"},
    {"docker images", "List images"},
    {"docker ps", "List containers"},
    {"docker exec", "Run a command in a running container"},
    {"docker build", "Build an image from a Dockerfile"},
    {"docker pull", "Pull an image or a repository from a registry"},
    {"docker push", "Push an image or a repository to a registry"},
    {"docker login", "Log in to a Docker registry"},
    {"docker logout", "Log out from a Docker registry"},
    {"docker tag", "Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE"},
    {"docker inspect", "Return low-level information on Docker objects"},
    {"docker logs", "Fetch the logs of a container"},
    {"docker commit", "Create a new image from a container's changes"},
    {"docker network", "Manage networks"},
    {"docker volume", "Manage volumes"},
    {"docker info", "Display system-wide information"},
    {"docker version", "Show the Docker version information"},
    {"docker swarm", "Manage Swarm"},
    {"docker node", "Manage Swarm nodes"},
    {"docker service", "Manage services"},
    {"docker stack", "Manage Docker stacks"},
    {"docker secret", "Manage Docker secrets"},
    {"docker config", "Manage Docker configs"},
    {"docker plugin", "Manage plugins"},
    {"docker container", "Manage containers"},
    {"docker image", "Manage images"},
    {"docker system", "Manage Docker"},
    {"docker context", "Manage contexts"},
    {"docker builder", "Manage builds"},
    {"docker checkpoint", "Manage checkpoints"},
    {"docker trust", "Manage trust on Docker images"},
    {"docker compose", "Define and run multi-container applications with Docker Compose"},
    {"docker save", "Save one or more images to a tar archive (streamed to STDOUT by default)"},
    {"docker load", "Load an image from a tar archive or STDIN"},
    {"docker history", "Show the history of an image"},
    {"docker prune", "Remove unused data"},
    {"docker attach", "Attach local standard input, output, and error streams to a running container"},
    {"docker diff", "Inspect changes to files or directories on a container’s filesystem"},
    {"docker events", "Get real time events from the server"},
    {"docker export", "Export a container’s filesystem as a tar archive"},
    {"docker import", "Import the contents from a tarball to create a filesystem image"},
    {"docker pause", "Pause all processes within one or more containers"},
    {"docker unpause", "Unpause all processes within one or more containers"},
    {"docker update", "Update configuration of one or more containers"},
    {"docker top", "Display the running processes of a container"},
    {"docker stats", "Display a live stream of container(s) resource usage statistics"},
    {"docker wait", "Block until one or more containers stop, then print their exit codes"},
    {"docker rename", "Rename a container"},
    {"docker cp", "Copy files/folders between a container and the local filesystem"},
    {"docker login", "Log in to a Docker registry"},
    {"docker logout", "Log out from a Docker registry"},
    {"docker search", "Search the Docker Hub for images"},
    {"docker volume create", "Create a volume"},
    {"docker volume inspect", "Display detailed information on one or more volumes"},
    {"docker volume ls", "List volumes"},
    {"docker volume prune", "Remove all unused local volumes"},
    {"docker volume rm", "Remove one or more volumes"},
    {"docker network create", "Create a network"},
    {"docker network inspect", "Display detailed information on one or more networks"},
    {"docker network ls", "List networks"},
    {"docker network prune", "Remove all unused networks"},
    {"docker network rm", "Remove one or more networks"},
    {"docker plugin create", "Create a plugin from a rootfs and configuration"},
    {"docker plugin disable", "Disable a plugin"},
    {"docker plugin enable", "Enable a plugin"},
    {"docker plugin inspect", "Display detailed information on one or more plugins"},
    {"docker plugin install", "Install a plugin"},
    {"docker plugin ls", "List plugins"},
    {"docker plugin push", "Push a plugin to a registry"},
    {"docker plugin rm", "Remove one or more plugins"},
    {"docker plugin set", "Change settings for a plugin"},
    {"docker plugin upgrade", "Upgrade an existing plugin"},
    {"docker secret create", "Create a secret from a file or STDIN as content"},
    {"docker secret inspect", "Display detailed information on one or more secrets"},
    {"docker secret ls", "List secrets"},
    {"docker secret rm", "Remove one or more secrets"},
    {"docker config create", "Create a config from a file or STDIN"},
    {"docker config inspect", "Display detailed information on one or more configs"},
    {"docker config ls", "List configs"},
    {"docker config rm", "Remove one or more configs"},
    {"docker swarm init", "Initialize a swarm"},
    {"docker swarm join", "Join a swarm as a node and/or manager"},
    {"docker swarm leave", "Leave the swarm"},
    {"docker swarm update", "Update the swarm"},
    {"docker node promote", "Promote one or more nodes to manager in the swarm"},
    {"docker node demote", "Demote one or more nodes from manager in the swarm"},
    {"docker node inspect", "Display detailed information on one or more nodes"},
    {"docker node ls", "List nodes in the swarm"},
    {"docker node rm", "Remove one or more nodes from the swarm"},
    {"docker service create", "Create a new service"},
    {"docker service inspect", "Display detailed information on one or more services"},
    {"docker service ls", "List services"},
    {"docker service rm", "Remove one or more services"},
    {"docker service scale", "Scale one or multiple replicated services"},
    {"docker service update", "Update a service"},
    {"docker stack deploy", "Deploy a new stack or update an existing stack"},
    {"docker stack rm", "Remove one or more stacks"},
    {"docker stack services", "List the services in the stack"},
    {"docker stack ps", "List the tasks in the stack"},
    {"docker stack ls", "List stacks"},
    {"docker checkpoint create", "Create a checkpoint from a running container"},
    {"docker checkpoint ls", "List checkpoints for a container"},
    {"docker checkpoint rm", "Remove a checkpoint"},
    {"docker checkpoint restore", "Restore a container from a checkpoint"},
    {"docker trust key generate", "Generate and load a signing key-pair"},
    {"docker trust key load", "Load a private key for signing tags"},
    {"docker trust signer add", "Add a signer to a repository"},
    {"docker trust signer remove", "Remove a signer from a repository"},
    {"docker trust inspect", "Return low-level information about keys and signatures"},
    {"docker trust revoke", "Revoke trust for an image"},
    {"docker trust sign", "Sign an image"},
    {"docker trust view", "View signed tags in a repository"},
    {"systemctl", "Examine and control the systemd system and service manager"},
    {"systemctl start", "Start (activate) one or more units"},
    {"systemctl stop", "Stop (deactivate) one or more units"},
    {"systemctl restart", "Restart one or more units"},
    {"systemctl reload", "Reload one or more units"},
    {"systemctl enable", "Enable one or more unit files"},
    {"systemctl disable", "Disable one or more unit files"},
    {"systemctl status", "Show runtime status of one or more units"},
    {"systemctl is-active", "Check whether units are active"},
    {"systemctl is-enabled", "Check whether unit files are enabled"},
    {"systemctl list-units", "List units currently in memory"},
    {"systemctl list-unit-files", "List unit files installed on the system"},
    {"systemctl daemon-reload", "Reload systemd manager configuration"},
    {"systemctl mask", "Mask one or more units"},
    {"systemctl unmask", "Unmask one or more units"},
    {"systemctl isolate", "Start one unit and stop all others"},
    {"systemctl kill", "Send a signal to processes of a unit"},
    {"systemctl show", "Show properties of one or more units/jobs or the manager"},
    {"systemctl cat", "Show unit file and drop-ins"},
    {"systemctl edit", "Edit a drop-in snippet or a whole unit file"},
    {"systemctl set-property", "Set one or more properties of a unit"},
    {"systemctl help", "Show manual for one or more units"},
    {"journalctl", "Query and display messages from the journal"},
    {"journalctl --boot", "Show messages from the current boot"},
    {"journalctl --list-boots", "Show a list of boots"},
    {"journalctl --unit", "Show messages for a specific unit"},
    {"journalctl --since", "Show messages since a specific time"},
    {"journalctl --until", "Show messages until a specific time"},
    {"journalctl --follow", "Follow new messages"},
    {"journalctl --output", "Change the output format"},
    {"journalctl --priority", "Show messages with a specific priority"},
    {"journalctl --grep", "Filter messages by a regular expression"},
    {"timedatectl", "Control the system time and date"},
    {"timedatectl status", "Show current time settings"},
    {"timedatectl set-time", "Set the system time"},
    {"timedatectl set-timezone", "Set the system timezone"},
    {"timedatectl list-timezones", "List available timezones"},
    {"timedatectl set-ntp", "Enable or disable Network Time Protocol (NTP) synchronization"},
    {"hostnamectl", "Control the system hostname"},
    {"hostnamectl status", "Show current hostname settings"},
    {"hostnamectl set-hostname", "Set the system hostname"},
    {"hostnamectl set-icon-name", "Set the system icon name"},
    {"hostnamectl set-chassis", "Set the system chassis type"},
    {"hostnamectl set-deployment", "Set the system deployment environment"},
    {"hostnamectl set-location", "Set the system location"},
    {"localectl", "Control the system locale and keyboard layout settings"},
    {"localectl status", "Show current locale settings"},
    {"localectl set-locale", "Set the system locale"},
    {"localectl list-locales", "List available locales"},
    {"localectl set-keymap", "Set the system keyboard layout"},
    {"localectl list-keymaps", "List available keyboard layouts"},
    {"loginctl", "Control the systemd login manager"},
    {"loginctl list-sessions", "List current sessions"},
    {"loginctl session-status", "Show status of a session"},
    {"loginctl terminate-session", "Terminate a session"},
    {"loginctl list-users", "List currently logged-in users"},
    {"loginctl user-status", "Show status of a user"},
    {"loginctl enable-linger", "Enable linger for a user"},
    {"loginctl disable-linger", "Disable linger for a user"},
    {"loginctl lock-session", "Lock a session"},
    {"loginctl unlock-session", "Unlock a session"},
    {"loginctl lock-sessions", "Lock all sessions"},
    {"loginctl unlock-sessions", "Unlock all sessions"},
    {"nmcli", "Command-line client for NetworkManager"},
    {"nmcli general", "General network management commands"},
    {"nmcli networking", "Control network connectivity"},
    {"nmcli radio", "Control radio transmitters"},
    {"nmcli connection", "Manage network connections"},
    {"nmcli device", "Manage network devices"},
    {"nmcli agent", "Run nmcli as a NetworkManager secret agent"},
    {"nmcli monitor", "Monitor NetworkManager changes"},    
    {"iwconfig", "Configure wireless network interfaces"},
    {"iwconfig essid", "Set the ESSID (network name)"},
    {"iwconfig mode", "Set the operating mode (Ad-Hoc, Managed, Master, Repeater, Secondary, Monitor)"},
    {"iwconfig freq", "Set the operating frequency or channel"},
    {"iwconfig ap", "Force the card to register to the Access Point given by the address"},
    {"iwconfig rate", "Forces the bit-rate to a specific value"},
    {"iwconfig txpower", "Set the transmit power"},
    {"iwconfig retry", "Set the maximum number of retries"},
    {"iwconfig rts", "Set the RTS/CTS threshold"},
    {"iwconfig frag", "Set the fragmentation threshold"},
    {"iwconfig key", "Set the encryption key"},
    {"iwconfig power", "Set the power management mode"},
    {"iwlist", "Get more detailed wireless information"},
    {"iwlist scan", "List available wireless networks"},
    {"iwlist frequency", "List the available frequencies in the device and the number of channels"},
    {"iwlist bitrate", "List the bit-rates supported by the device"},
    {"iwlist encryption", "List the encryption key sizes supported and display all the encryption keys available in the device"},
    {"iwlist power", "List the various Power Management attributes and modes of the device"},
    {"iwlist txpower", "List the various Transmit Powers available on the device"},
    {"iwlist retry", "List the transmit retry limits and retry lifetime"},
    {"traceroute", "Print the route packets take to the network host"},
    {"mtr", "Network diagnostic tool"},
    {"dig", "DNS lookup"},
    {"nslookup", "Query Internet name servers interactively"},
    {"host", "DNS lookup utility"},
    {"rsync", "Remote file and directory synchronization"},
    {"ftp", "File Transfer Protocol client"},
    {"ftp open", "Connect to a remote FTP server"},
    {"ftp close", "Terminate an FTP session"},
    {"ftp put", "Send one file"},
    {"ftp mput", "Send multiple files"},
    {"ftp get", "Receive one file"},
    {"ftp mget", "Receive multiple files"},
    {"ftp delete", "Delete a file on the remote machine"},
    {"ftp mdelete", "Delete multiple files on the remote machine"},
    {"ftp rename", "Rename a file on the remote machine"},
    {"ftp mkdir", "Make a directory on the remote machine"},
    {"ftp rmdir", "Remove a directory on the remote machine"},
    {"ftp ls", "List the contents of a directory on the remote machine"},
    {"ftp lcd", "Change the local working directory"},
    {"ftp cd", "Change the remote working directory"},
    {"ftp ascii", "Set the file transfer type to ASCII"},
    {"ftp binary", "Set the file transfer type to binary"},
    {"ftp passive", "Enter passive transfer mode"},
    {"ftp active", "Enter active transfer mode"},
    {"sftp", "Secure File Transfer Protocol"},
    {"sftp get", "Download files from the server"},
    {"sftp put", "Upload files to the server"},
    {"sftp ls", "List files on the server"},
    {"sftp cd", "Change directory on the server"},
    {"sftp lcd", "Change local directory"},
    {"sftp mkdir", "Create a directory on the server"},
    {"sftp rmdir", "Remove a directory on the server"},
    {"sftp rm", "Delete a file on the server"},
    {"sftp rename", "Rename a file on the server"},
    {"sftp chmod", "Change file permissions on the server"},
    {"sftp chown", "Change file owner on the server"},
    {"sftp chgrp", "Change file group on the server"},
    {"sftp lls", "List local files"},
    {"sftp lmkdir", "Create a local directory"},
    {"sftp lrm", "Delete a local file"},
    {"sftp lrename", "Rename a local file"},
    {"sftp lchmod", "Change local file permissions"},
    {"sftp lchown", "Change local file owner"},
    {"sftp lchgrp", "Change local file group"},
    {"telnet", "User interface to the TELNET protocol"},
    {"telnet open", "Connect to a remote host"},
    {"telnet close", "Close the current connection"},
    {"telnet quit", "Exit telnet"},
    {"telnet send", "Send special characters to the remote host"},
    {"telnet status", "Print status information"},
    {"telnet set", "Set telnet options"},
    {"telnet unset", "Unset telnet options"},
    {"telnet toggle", "Toggle telnet options"},
    {"telnet mode", "Set the transmission mode"},
    {"telnet display", "Display operating parameters"},
    {"telnet environ", "Change environment variables"},
    {"nc", "Netcat, a versatile networking tool"},
    {"nmap", "Network exploration tool and security/port scanner"},
    {"tcpdump", "Command-line packet analyzer"},
    {"wireshark", "Network protocol analyzer"},
    {"iptables", "Administration tool for IPv4 packet filtering and NAT"},
    {"firewalld", "A firewall management tool"},
    {"ufw", "Uncomplicated Firewall, a frontend for iptables"},
    {"ufw enable", "Enable the firewall"},
    {"ufw disable", "Disable the firewall"},
    {"ufw status", "Show the firewall status"},
    {"ufw allow", "Allow a service or port through the firewall"},
    {"ufw deny", "Deny a service or port through the firewall"},
    {"ufw reject", "Reject a service or port through the firewall"},
    {"ufw limit", "Limit the rate of connections"},
    {"ufw delete", "Delete a rule"},
    {"ufw reset", "Reset the firewall to default settings"},
    {"ufw reload", "Reload the firewall"},
    {"ufw logging", "Set the logging level"},
    {"fail2ban", "Ban IPs that show malicious signs"},
    {"logrotate", "Rotates, compresses, and mails system logs"},
    {"cron", "Daemon to execute scheduled commands"},
    {"cron start", "Start the cron daemon"},
    {"cron stop", "Stop the cron daemon"},
    {"cron restart", "Restart the cron daemon"},
    {"cron reload", "Reload the cron daemon configuration"},
    {"cron status", "Show the status of the cron daemon"},
    {"cron list", "List all scheduled cron jobs"},
    {"cron add", "Add a new cron job"},
    {"cron remove", "Remove an existing cron job"},
    {"cron edit", "Edit an existing cron job"},
    {"anacron", "Run commands periodically"},
    {"systemd-analyze", "Analyze system boot-up performance"},
    {"systemd-analyze blame", "Show time taken to initialize each service"},
    {"systemd-analyze critical-chain", "Show the critical chain of services"},
    {"systemd-analyze plot", "Generate an SVG plot of boot sequence"},
    {"systemd-analyze dump", "Show complete state of the systemd manager"},
    {"systemd-analyze verify", "Check unit files for correctness"},
    {"systemd-analyze security", "Analyze security of unit files"},
    {"systemd-analyze time", "Show time taken to boot the system"},
    {"pkill", "Send signal to processes based on name and other attributes"},
    {"pgrep", "Look up or signal processes based on name and other attributes"},
    {"nice", "Run a program with modified scheduling priority"},
    {"renice", "Alter priority of running processes"},
    {"ionice", "Set or get I/O scheduling class and priority"},
    {"watch", "Execute a program periodically, showing output fullscreen"},
    {"screen", "Terminal multiplexer"},
    {"tmux", "Terminal multiplexer"},
    {"nohup", "Run a command immune to hangups, with output to a non-tty"},
    {"disown", "Remove jobs from current shell"},
    {"ethtool", "Display or change Ethernet device settings"},
    {"arp", "Manipulate the system ARP cache"},
    {"whois", "Client for the whois directory service"},
    {"ipcalc", "Calculate IP information for a given IP address"},
    {"netcat", "Utility for reading from and writing to network connections using TCP or UDP"},
    {"arping", "Send ARP REQUEST to a neighbor host"},
    {"iw", "Show/manipulate wireless devices and their configuration"},
    {"bridge", "Show/manipulate bridge addresses and devices"},
    {"tc", "Show/manipulate traffic control settings"},
    {"ipset", "Administration tool for IP sets"},
    {"ip rule", "Routing policy database management"},
    {"ip addr", "Show/manipulate IP addresses"},
    {"ip link", "Show/manipulate network devices"},
    {"ip route", "Show/manipulate routing tables"},
    {"ip neigh", "Show/manipulate neighbor objects"},
    {"ip maddr", "Show/manipulate multicast addresses"},
    {"ip monitor", "Watch for netlink messages"},
    {"ip tunnel", "Show/manipulate tunnel devices"},
    {"ip xfrm", "Show/manipulate IPSec policies"},
    {"ip netns", "Show/manipulate network namespaces"},
    {"ip vrf", "Show/manipulate VRF devices"},
    {"ip link set", "Change device attributes"},
    {"ip link add", "Add a new device"},
    {"ip link delete", "Delete a device"},
    {"ip link show", "Display device attributes"},
    {"ip link set dev", "Change device attributes"},
    {"ip link set up", "Enable a device"},
    {"ip link set down", "Disable a device"},
    {"ip link set mtu", "Change device MTU"},
    {"ip link set address", "Change device MAC address"},
    {"ip link set master", "Set master device"},
    {"ip link set nomaster", "Unset master device"},
    {"ip link set type", "Change device type"},
    {"ip link set netns", "Move device to network namespace"},
    {"ip link set alias", "Set device alias"},
    {"ip link set group", "Set device group"},
    {"ip link set txqueuelen", "Change device transmit queue length"},
    {"ip link set vf", "Change virtual function attributes"},
    {"ip link set xdp", "Attach/detach XDP program"},
    {"git init", "Create an empty Git repository or reinitialize an existing one"},
    {"git clone", "Clone a repository into a new directory"},
    {"git add", "Add file contents to the index"},
    {"git commit", "Record changes to the repository"},
    {"git status", "Show the working tree status"},
    {"git push", "Update remote refs along with associated objects"},
    {"git pull", "Fetch from and integrate with another repository or a local branch"},
    {"git fetch", "Download objects and refs from another repository"},
    {"git merge", "Join two or more development histories together"},
    {"git branch", "List, create, or delete branches"},
    {"git checkout", "Switch branches or restore working tree files"},
    {"git log", "Show commit logs"},
    {"git diff", "Show changes between commits, commit and working tree, etc"},
    {"git reset", "Reset current HEAD to the specified state"},
    {"git rm", "Remove files from the working tree and from the index"},
    {"git mv", "Move or rename a file, a directory, or a symlink"},
    {"git tag", "Create, list, delete or verify a tag object signed with GPG"},
    {"git stash", "Stash the changes in a dirty working directory away"},
    {"git rebase", "Reapply commits on top of another base tip"},
    {"git remote", "Manage set of tracked repositories"},
    {"git show", "Show various types of objects"},
    {"git archive", "Create an archive of files from a named tree"},
    {"git bisect", "Use binary search to find the commit that introduced a bug"},
    {"git blame", "Show what revision and author last modified each line of a file"},
    {"git cherry-pick", "Apply the changes introduced by some existing commits"},
    {"git grep", "Print lines matching a pattern"},
    {"git reflog", "Manage reflog information"},
    {"git submodule", "Initialize, update or inspect submodules"},
    {"git gc", "Cleanup unnecessary files and optimize the local repository"},
    {"git fsck", "Verifies the connectivity and validity of the objects in the database"},
    {"git clean", "Remove untracked files from the working tree"},
    {"git config", "Get and set repository or global options"},
    {"git describe", "Give an object a human-readable name based on an available ref"},
    {"git shortlog", "Summarize git log output"},
    {"git rev-parse", "Pick out and massage parameters"},
    {"git ls-tree", "List the contents of a tree object"},
    {"git update-index", "Register file contents in the working directory to the index"},
    {"git symbolic-ref", "Read, modify and delete symbolic refs"},
    {"git worktree", "Manage multiple working trees"},
    {"git notes", "Add or inspect object notes"},
    {"git rerere", "Reuse recorded resolution of conflicted merges"},
    {"git range-diff", "Compare two commit ranges"},
    {"git replace", "Create, list, delete refs to replace objects"},
    {"git verify-commit", "Check the GPG signature of commits"},
    {"git verify-tag", "Check the GPG signature of tags"},
    {"git whatchanged", "Show logs with difference each commit introduces"},
    {"git instaweb", "Instantly browse your working repository in gitweb"},
    {"git daemon", "A really simple server for Git repositories"},
    {"git bundle", "Move objects and refs by archive"},
    {"git filter-branch", "Rewrite branches"},
    {"git mergetool", "Run merge conflict resolution tools to resolve merge conflicts"},
    {"git citool", "Graphical alternative to git-commit"},
    {"git gui", "A portable graphical interface to Git"},
    {"gitk", "The Git repository browser"},
    {"git instaweb", "Instantly browse your working repository in gitweb"},
    {"git archive", "Create an archive of files from a named tree"},
    {"git apply", "Apply a patch to files and/or to the index"},
    {"git am", "Apply a series of patches from a mailbox"},
    {"git cherry", "Find commits yet to be applied to upstream"},
    {"git format-patch", "Prepare patches for e-mail submission"},
    {"git send-email", "Send a collection of patches as emails"},
    {"git request-pull", "Generate a summary of pending changes"},
    {"git submodule", "Initialize, update or inspect submodules"},
    {"git svn", "Bidirectional operation between a Subversion repository and Git"},
    {"git fast-import", "Backend for fast Git data importers"},
    {"git fast-export", "Git data exporter"},
    {"git daemon", "A really simple server for Git repositories"},
    {"git instaweb", "Instantly browse your working repository in gitweb"},
    {"git instaweb", "Instantly browse your working repository in gitweb"},
    {"lazygit", "A simple terminal UI for git commands"},
    {"fzf", "A command-line fuzzy finder"},
    {"rg", "ripgrep, a line-oriented search tool that recursively searches your current directory for a regex pattern"},
    {"postman", "A collaboration platform for API development"},
    {"http", "HTTPie, a command line HTTP client"},
    {"jq", "A lightweight and flexible command-line JSON processor"},
    {"scp", "Secure copy (remote file copy program)"},
    {"svn", "Subversion version control system"},
    {"hg", "Mercurial version control system"},
    {"bzr", "Bazaar version control system"},
    {"podman", "Tool for managing OCI containers and pods"},
    {"rkt", "App Container runtime"},
    {"kubernetes", "Container orchestration"},
    {"minikube", "Run Kubernetes locally"},
    {"helm", "The Kubernetes Package Manager"},
    {"kubeadm", "Bootstrap a Kubernetes cluster"},
    {"kops", "Kubernetes Operations"},
    {"kubectx", "Switch between clusters on kubectl"},
    {"kubens", "Switch between Kubernetes namespaces"},
    {"kubectl", "Kubernetes command-line tool"},
    {"kubectl get", "Kubernetes command-line tool"},
    {"kubectl describe", "Kubernetes command-line tool"},
    {"kubectl create", "Kubernetes command-line tool"},
    {"kubectl delete", "Kubernetes command-line tool"},
    {"kubectl apply", "Kubernetes command-line tool"},
    {"kubectl logs", "Kubernetes command-line tool"},
    {"kubectl exec", "Kubernetes command-line tool"},
    {"kubectl scale", "Kubernetes command-line tool"},
    {"kubectl expose", "Kubernetes command-line tool"},
    {"vagrant", "Build and maintain portable virtual software development environments"},
    {"vagrant init", "Build and maintain portable virtual software development environments"},
    {"vagrant up", "Build and maintain portable virtual software development environments"},
    {"vagrant halt", "Build and maintain portable virtual software development environments"},
    {"vagrant destroy", "Build and maintain portable virtual software development environments"},
    {"vagrant ssh", "Build and maintain portable virtual software development environments"},
    {"vagrant status", "Build and maintain portable virtual software development environments"},
    {"vagrant provision", "Build and maintain portable virtual software development environments"},
    {"vagrant reload", "Build and maintain portable virtual software development environments"},
    {"packer", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer build", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer validate", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer inspect", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer fix", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer version", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer fmt", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer build", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer validate", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer inspect", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer fix", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer version", "Create identical machine images for multiple platforms from a single source configuration"},
    {"packer fmt", "Create identical machine images for multiple platforms from a single source configuration"},
    {"terraform", "Infrastructure as Code"},
    {"terraform init", "Infrastructure as Code"},
    {"terraform plan", "Infrastructure as Code"},
    {"terraform apply", "Infrastructure as Code"},
    {"terraform destroy", "Infrastructure as Code"},
    {"terraform validate", "Infrastructure as Code"},
    {"terraform fmt", "Infrastructure as Code"},
    {"terraform show", "Infrastructure as Code"},
    {"terraform state", "Infrastructure as Code"},
    {"terraform output", "Infrastructure as Code"},
    {"ansible", "Automate IT infrastructure"},
    {"ansible-playbook", "Automate IT infrastructure"},
    {"ansible-galaxy", "Automate IT infrastructure"},
    {"ansible-vault", "Automate IT infrastructure"},
    {"ansible-doc", "Automate IT infrastructure"},
    {"ansible-config", "Automate IT infrastructure"},
    {"ansible-inventory", "Automate IT infrastructure"},
    {"chef", "Automate how infrastructure is configured, deployed, and managed"},
    {"chef-client", "Run the Chef Infra Client"},
    {"chef-solo", "Run the Chef Infra Client in solo mode"},
    {"knife", "Command-line tool for interacting with the Chef Infra Server"},
    {"chef-server-ctl", "Manage the Chef Infra Server"},
    {"chef-apply", "Apply a single recipe to a system"},
    {"chef-shell", "Interactive Chef Infra Client shell"},
    {"chef-zero", "In-memory Chef Infra Server for testing"},
    {"puppet", "Automate the delivery and operation of the software that powers your business"},
    {"puppet apply", "Apply Puppet manifests to the local system"},
    {"puppet agent", "Manage a Puppet agent"},
    {"puppet cert", "Manage Puppet certificates"},
    {"puppet config", "Manage Puppet configuration settings"},
    {"puppet describe", "Describe Puppet resource types"},
    {"puppet device", "Manage Puppet devices"},
    {"puppet doc", "Display Puppet documentation"},
    {"puppet facts", "Retrieve and display facts about the system"},
    {"puppet filebucket", "Manage Puppet file buckets"},
    {"puppet help", "Display help for Puppet commands"},
    {"puppet lookup", "Lookup data in Hiera"},
    {"puppet module", "Manage Puppet modules"},
    {"puppet parser", "Validate and parse Puppet manifests"},
    {"puppet resource", "Manage resources on the system"},
    {"puppet server", "Manage the Puppet server"},
    {"puppet status", "Display the status of Puppet services"},
    {"puppet task", "Run tasks on remote systems"},
    {"puppet test", "Run tests on Puppet code"},
    {"puppet type", "Manage Puppet resource types"},
}