package network

// Network represents a networking command and its description
type Network struct {
    Name        string
    Description string
}

// List of networking commands with descriptions
var Words = []Network{
    {"ping", "Send ICMP ECHO_REQUEST to network hosts"},
    {"ifconfig", "Configure a network interface"},
    {"ip", "Show/manipulate routing, devices, policy routing and tunnels"},
    {"netstat", "Print network connections, routing tables, interface statistics, masquerade connections, and multicast memberships"},
    {"ss", "Another utility to investigate sockets"},
    {"traceroute", "Print the route packets take to the network host"},
    {"mtr", "Network diagnostic tool"},
    {"dig", "DNS lookup"},
    {"nslookup", "Query Internet name servers interactively"},
    {"host", "DNS lookup utility"},
    {"rsync", "Remote file and directory synchronization"},
    {"ftp", "File Transfer Protocol client"},
    {"sftp", "Secure File Transfer Protocol"},
    {"telnet", "User interface to the TELNET protocol"},
    {"nc", "Netcat, a versatile networking tool"},
    {"nmap", "Network exploration tool and security/port scanner"},
    {"tcpdump", "Command-line packet analyzer"},
    {"wireshark", "Network protocol analyzer"},
    {"iptables", "Administration tool for IPv4 packet filtering and NAT"},
    {"firewalld", "A firewall management tool"},
    {"ufw", "Uncomplicated Firewall, a frontend for iptables"},
    {"fail2ban", "Ban IPs that show malicious signs"},
    {"nmcli", "Command-line client for NetworkManager"},
    {"iwconfig", "Configure wireless network interfaces"},
    {"iwlist", "Get more detailed wireless information"},
    {"ethtool", "Display or change Ethernet device settings"},
    {"route", "Show/manipulate the IP routing table"},
    {"arp", "Manipulate the system ARP cache"},
    {"hostname", "Show or set the system's host name"},
    {"curl", "Transfer data from or to a server"},
    {"wget", "Non-interactive network downloader"},
    {"scp", "Secure copy (remote file copy program)"},
    {"ssh", "OpenSSH SSH client (remote login program)"},
    {"whois", "Client for the whois directory service"},
    {"ipcalc", "Calculate IP information for a given IP address"},
    {"netcat", "Utility for reading from and writing to network connections using TCP or UDP"},
    {"route", "Show/manipulate the IP routing table"},
    {"arping", "Send ARP REQUEST to a neighbor host"},
    {"iw", "Show/manipulate wireless devices and their configuration"},
    {"bridge", "Show/manipulate bridge addresses and devices"},
    {"tc", "Show/manipulate traffic control settings"},
    {"ipset", "Administration tool for IP sets"},
    {"ip rule", "Routing policy database management"},
    {"ip addr", "Show/manipulate IP addresses"},
    {"ip link", "Show/manipulate network devices"},
    {"ip route", "Show/manipulate routing tables"},
    {"ip neigh", "Show/manipulate neighbor objects"},
    {"ip maddr", "Show/manipulate multicast addresses"},
    {"ip monitor", "Watch for netlink messages"},
    {"ip tunnel", "Show/manipulate tunnel devices"},
    {"ip xfrm", "Show/manipulate IPSec policies"},
    {"ip netns", "Show/manipulate network namespaces"},
    {"ip vrf", "Show/manipulate VRF devices"},
    {"ip link set", "Change device attributes"},
    {"ip link add", "Add a new device"},
    {"ip link delete", "Delete a device"},
    {"ip link show", "Display device attributes"},
    {"ip link set dev", "Change device attributes"},
    {"ip link set up", "Enable a device"},
    {"ip link set down", "Disable a device"},
    {"ip link set mtu", "Change device MTU"},
    {"ip link set address", "Change device MAC address"},
    {"ip link set master", "Set master device"},
    {"ip link set nomaster", "Unset master device"},
    {"ip link set type", "Change device type"},
    {"ip link set netns", "Move device to network namespace"},
    {"ip link set alias", "Set device alias"},
    {"ip link set group", "Set device group"},
    {"ip link set txqueuelen", "Change device transmit queue length"},
    {"ip link set vf", "Change virtual function attributes"},
    {"ip link set xdp", "Attach/detach XDP program"},
}