package flags

// Flag represents a command and its flags
type Flag struct {
    Name        string
    Description string
}

var Words = []Flag{
    {"sudo", "Flags: -u (user), -s (shell), -b (background)"},
    {"cat", "Flags: -n (number lines), -b (number non-blank lines), -s (squeeze blank)"},
    {"ls", "Flags: -l (long listing), -a (all files), -h (human-readable)"},
    {"cd", "Flags: No flags available"},
    {"pwd", "Flags: -L (logical), -P (physical)"},
    {"touch", "Flags: -a (change access time), -m (change modification time), -c (do not create)"},
    {"mkdir", "Flags: -p (parents), -v (verbose), -m (mode)"},
    {"rm", "Flags: -r (recursive), -f (force), -v (verbose)"},
    {"cp", "Flags: -r (recursive), -i (interactive), -v (verbose)"},
    {"mv", "Flags: -i (interactive), -f (force), -v (verbose)"},
    {"clear", "Flags: No flags available"},
    {"exit", "Flags: No flags available"},
    {"echo", "Flags: -n (no newline), -e (enable interpretation of backslash escapes)"},
    {"man", "Flags: -k (keyword search), -f (whatis), -a (all)"},
    {"grep", "Flags: -i (ignore case), -r (recursive), -v (invert match)"},
    {"find", "Flags: -name (name pattern), -type (file type), -exec (execute command)"},
    {"chmod", "Flags: -R (recursive), -v (verbose), -c (changes)"},
    {"chown", "Flags: -R (recursive), -v (verbose), -c (changes)"},
    {"df", "Flags: -h (human-readable), -T (print file system type), -i (inodes)"},
    {"du", "Flags: -h (human-readable), -s (summarize), -a (all files)"},
    {"head", "Flags: -n (number of lines), -c (number of bytes), -q (quiet)"},
    {"tail", "Flags: -n (number of lines), -f (follow), -c (number of bytes)"},
    {"tar", "Flags: -c (create), -x (extract), -v (verbose)"},
    {"wget", "Flags: -O (output file), -q (quiet), -r (recursive)"},
    {"curl", "Flags: -o (output file), -I (head), -L (location)"},
    {"ps", "Flags: -e (all processes), -f (full format), -u (user)"},
    {"kill", "Flags: -s (signal), -l (list signals), -p (process)"},
    {"top", "Flags: -b (batch mode), -n (number of iterations), -u (user)"},
    {"htop", "Flags: -d (delay), -u (user), -p (pid)"},
    {"ssh", "Flags: -l (login name), -p (port), -i (identity file)"},
    {"scp", "Flags: -r (recursive), -P (port), -i (identity file)"},
    {"nano", "Flags: -B (backup), -m (mouse support), -i (auto-indent)"},
    {"vim", "Flags: -u (vimrc file), -N (no compatible), -e (ex mode)"},
    {"apt-get", "Flags: -y (assume yes), -q (quiet), -d (download only)"},
    {"yum", "Flags: -y (assume yes), -q (quiet), -v (verbose)"},
    {"ping", "Flags: -c (count), -i (interval), -t (ttl)"},
    {"ifconfig", "Flags: -a (all interfaces), -s (short display), -v (verbose)"},
    {"ip", "Flags: -s (statistics), -d (details), -r (resolve)"},
    {"netstat", "Flags: -a (all), -t (tcp), -u (udp)"},
    {"ss", "Flags: -t (tcp), -u (udp), -a (all)"},
    {"mount", "Flags: -t (type), -o (options), -v (verbose)"},
    {"umount", "Flags: -f (force), -l (lazy), -v (verbose)"},
    {"uname", "Flags: -a (all), -r (kernel release), -v (kernel version)"},
    {"uptime", "Flags: No flags available"},
    {"whoami", "Flags: No flags available"},
    {"hostname", "Flags: -i (ip address), -f (fqdn), -d (domain)"},
    {"history", "Flags: -c (clear), -d (delete), -a (append)"},
    {"alias", "Flags: No flags available"},
    {"unalias", "Flags: -a (all)"},
    {"env", "Flags: No flags available"},
    {"export", "Flags: No flags available"},
    {"source", "Flags: No flags available"},
    {"su", "Flags: -c (command), -l (login), -s (shell)"},
    {"passwd", "Flags: -d (delete), -e (expire), -l (lock)"},
    {"useradd", "Flags: -m (create home), -s (shell), -G (groups)"},
    {"usermod", "Flags: -l (login), -G (groups), -s (shell)"},
    {"userdel", "Flags: -r (remove home), -f (force)"},
    {"groupadd", "Flags: -g (gid), -r (system group)"},
    {"groupmod", "Flags: -n (new name), -g (gid)"},
    {"groupdel", "Flags: No flags available"},
    {"crontab", "Flags: -e (edit), -l (list), -r (remove)"},
    {"at", "Flags: -f (file), -m (mail), -v (verbose)"},
    {"jobs", "Flags: -l (long), -p (process group id), -n (notify)"},
    {"bg", "Flags: No flags available"},
    {"fg", "Flags: No flags available"},
    {"killall", "Flags: -i (interactive), -v (verbose), -w (wait)"},
    {"xargs", "Flags: -n (max args), -P (max procs), -I (replace string)"},
    {"tee", "Flags: -a (append), -i (ignore interrupts)"},
    {"diff", "Flags: -u (unified), -c (context), -i (ignore case)"},
    {"patch", "Flags: -p (strip), -R (reverse), -N (ignore already applied)"},
    {"sed", "Flags: -n (quiet), -e (expression), -i (in-place)"},
    {"awk", "Flags: -F (field separator), -v (variable), -f (file)"},
    {"tr", "Flags: -d (delete), -s (squeeze), -c (complement)"},
    {"cut", "Flags: -f (fields), -d (delimiter), -c (characters)"},
    {"sort", "Flags: -r (reverse), -n (numeric), -k (key)"},
    {"uniq", "Flags: -c (count), -d (repeated), -u (unique)"},
    {"wc", "Flags: -l (lines), -w (words), -c (bytes)"},
    {"basename", "Flags: -s (suffix)"},
    {"dirname", "Flags: No flags available"},
    {"readlink", "Flags: -f (canonicalize), -e (exist), -m (multiple)"},
    {"ln", "Flags: -s (symbolic), -f (force), -v (verbose)"},
    {"stat", "Flags: -f (file system), -t (terse), -c (format)"},
    {"file", "Flags: -b (brief), -i (mime), -z (decompress)"},
    {"strings", "Flags: -a (all), -n (number), -t (radix)"},
    {"md5sum", "Flags: -c (check), -b (binary), -t (text)"},
    {"sha256sum", "Flags: -c (check), -b (binary), -t (text)"},
    {"gzip", "Flags: -d (decompress), -k (keep), -r (recursive)"},
    {"gunzip", "Flags: -k (keep), -r (recursive)"},
    {"bzip2", "Flags: -d (decompress), -k (keep), -v (verbose)"},
    {"bunzip2", "Flags: -k (keep), -v (verbose)"},
    {"zip", "Flags: -r (recursive), -q (quiet), -v (verbose)"},
    {"unzip", "Flags: -l (list), -t (test), -d (directory)"},
    {"rar", "Flags: -a (add), -x (extract), -v (volume)"},
    {"unrar", "Flags: -x (extract), -l (list), -v (verbose)"},
    {"7z", "Flags: -a (add), -x (extract), -t (type)"},
    {"7za", "Flags: -a (add), -x (extract), -t (type)"},
    {"7zr", "Flags: -a (add), -x (extract), -t (type)"},
    {"free", "Flags: -h (human-readable), -m (megabytes), -g (gigabytes)"},
    {"who", "Flags: -a (all), -b (boot), -q (count)"},
    {"last", "Flags: -n (number), -R (no hostname), -x (system)"},
    {"dmesg", "Flags: -C (clear), -c (read and clear), -T (human-readable)"},
    {"lsblk", "Flags: -f (file system), -o (output), -d (dependencies)"},
    {"blkid", "Flags: -p (probe), -s (show), -o (output)"},
    {"fdisk", "Flags: -l (list), -u (units), -c (compatibility)"},
    {"mkfs", "Flags: -t (type), -c (check), -v (verbose)"},
    {"fsck", "Flags: -a (auto), -r (interactive), -y (yes)"},
    {"parted", "Flags: -l (list), -s (script), -a (align)"},
    {"dd", "Flags: if (input file), of (output file), bs (block size)"},
    {"sync", "Flags: No flags available"},
    {"shutdown", "Flags: -h (halt), -r (reboot), -c (cancel)"},
    {"reboot", "Flags: No flags available"},
    {"systemctl", "Flags: -t (type), -a (all), -l (full)"},
    {"journalctl", "Flags: -f (follow), -u (unit), -p (priority)"},
    {"timedatectl", "Flags: -s (set), -p (print), -l (list)"},
    {"hostnamectl", "Flags: -s (set), -p (print), -l (list)"},
    {"localectl", "Flags: -s (set), -p (print), -l (list)"},
    {"loginctl", "Flags: -s (set), -p (print), -l (list)"},
    {"nmcli", "Flags: -t (terse), -p (pretty), -m (mode)"},
    {"iwconfig", "Flags: -a (all), -d (debug), -s (status)"},
    {"iwlist", "Flags: -a (all), -d (debug), -s (status)"},
    {"traceroute", "Flags: -m (max hops), -q (queries), -w (wait)"},
    {"mtr", "Flags: -r (report), -c (count), -i (interval)"},
    {"dig", "Flags: -t (type), -x (reverse), -p (port)"},
    {"nslookup", "Flags: -type (type), -timeout (timeout), -port (port)"},
    {"host", "Flags: -t (type), -v (verbose), -a (all)"},
    {"rsync", "Flags: -a (archive), -v (verbose), -z (compress)"},
    {"ftp", "Flags: -v (verbose), -n (no auto-login), -i (interactive)"},
    {"sftp", "Flags: -b (batch), -C (compress), -o (option)"},
    {"telnet", "Flags: -a (automatic login), -e (escape), -l (user)"},
    {"nc", "Flags: -l (listen), -u (udp), -v (verbose)"},
    {"nmap", "Flags: -sS (TCP SYN scan), -O (OS detection), -v (verbose)"},
    {"tcpdump", "Flags: -i (interface), -n (numeric), -v (verbose)"},
    {"wireshark", "Flags: -i (interface), -k (start capture), -f (filter)"},
    {"iptables", "Flags: -A (append), -D (delete), -L (list)"},
    {"firewalld", "Flags: -q (quiet), -v (verbose), -h (help)"},
    {"ufw", "Flags: -a (allow), -d (deny), -r (reject)"},
    {"fail2ban", "Flags: -d (debug), -q (quiet), -v (verbose)"},
    {"logrotate", "Flags: -d (debug), -f (force), -v (verbose)"},
    {"cron", "Flags: No flags available"},
    {"anacron", "Flags: -d (debug), -s (safe), -u (update)"},
    {"systemd-analyze", "Flags: -p (property), -t (type), -f (filter)"},
    {"pkill", "Flags: -u (user), -t (terminal), -x (exact)"},
    {"pgrep", "Flags: -u (user), -t (terminal), -x (exact)"},
    {"nice", "Flags: -n (adjustment)"},
    {"renice", "Flags: -n (adjustment), -p (pid), -u (user)"},
    {"ionice", "Flags: -c (class), -n (priority), -p (pid)"},
    {"watch", "Flags: -n (interval), -d (differences), -t (no title)"},
    {"screen", "Flags: -d (detach), -r (reattach), -S (session name)"},
    {"tmux", "Flags: -d (detach), -r (reattach), -S (session name)"},
    {"nohup", "Flags: No flags available"},
    {"disown", "Flags: -h (not remove from job table)"},
}